---
title: "progress-report-jennifergodbersen"
author: "Jennifer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
library(Lahman)
head(HallOfFame, 100)
```

```{r}
library(magrittr)
library(ggplot2)

HallOfFame %>%
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2023))
```



```{r}
library(rvest)
url <- "https://www.baseball-reference.com/awards/hof_2023.shtml"
html <- read_html(url)
html

```

```{r}
tables <- html %>% html_table(fill=TRUE)
tables %>% str()
```

```{r}
table2023 <- tables[[1]]

table2023 %>% head()
```

```{r}
#Fix column names in table2023

# Transpose the first row of table2023 to get column names
column_names <- t(table2023[1, ])

# Set column names of table2023 to the transposed row
colnames(table2023) <- column_names

# Remove the first row from table2023
table2023 <- table2023[-1, ]
table2023 <-  table2023[, c(2, 4)]

# Convert to numeric
table2023$Votes <- as.numeric(table2023$Votes)

```

```{r}
table2023 <- table2023 %>% 
  mutate(
    playerID = Name,
    yearID = 2023,
    votedBy = "BBWAA",
    ballots = 389,
    needed = 202,
    votes = table2023$Votes,
    inducted = ifelse(Votes > 292, "Y", "N"), 
    category = NA,
    needed_note = NA
  ) 

table2023 <- table2023[, -c(1, 2)]
table2023
```

```{r}
library(dplyr)
hof_including_2023 <- bind_rows(HallOfFame, table2023)
hof_including_2023
```
```{r}
#replot up to 2023
hof_including_2023 %>%
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2023))
```

